Create README.md
Hello,

I struck with below error could someone help me with this error.

Error: Invalid template interpolation value
│
│   on ../../../../../modules/google_kubernetes_engine/asm/hub.tf line 21, in resource "google_gke_hub_membership" "membership":
│   21:   membership_id = "${data.google_container_cluster.asm.name}-membership"
│     ├────────────────
│     │ data.google_container_cluster.asm.name is null
│
│ The expression result is null. Cannot include a null value in a string template.
╵
╷
│ Error: Invalid template interpolation value
│
│   on ../../../../../modules/google_kubernetes_engine/asm/hub.tf line 24, in resource "google_gke_hub_membership" "membership":
│   24:      resource_link = "//container.googleapis.com/${data.google_container_cluster.asm.id}"
│     ├────────────────
│     │ data.google_container_cluster.asm.id is null
│
│ The expression result is null. Cannot include a null value in a string template.
╵